insert into public.zip_market_lookup (zip_prefix, market_code, city, state_code)
values
  ('070', 'new_york_ny', 'Newark', 'NJ'),
  ('071', 'new_york_ny', 'Newark', 'NJ'),
  ('073', 'new_york_ny', 'Jersey City', 'NJ'),
  ('104', 'new_york_ny', 'Bronx', 'NY'),
  ('112', 'new_york_ny', 'Brooklyn', 'NY'),
  ('113', 'new_york_ny', 'Queens', 'NY'),
  ('114', 'new_york_ny', 'Queens', 'NY'),
  ('115', 'new_york_ny', 'Long Island', 'NY'),
  ('116', 'new_york_ny', 'Far Rockaway', 'NY'),
  ('117', 'new_york_ny', 'Long Island', 'NY'),
  ('190', 'philadelphia_pa', 'Philadelphia', 'PA'),
  ('193', 'philadelphia_pa', 'Philadelphia', 'PA'),
  ('194', 'philadelphia_pa', 'Philadelphia', 'PA'),
  ('201', 'washington_dc', 'Northern Virginia', 'VA'),
  ('207', 'washington_dc', 'Prince Georges County', 'MD'),
  ('208', 'washington_dc', 'Montgomery County', 'MD'),
  ('209', 'washington_dc', 'Silver Spring', 'MD'),
  ('210', 'washington_dc', 'Columbia', 'MD'),
  ('211', 'washington_dc', 'Baltimore Suburbs', 'MD'),
  ('212', 'washington_dc', 'Baltimore', 'MD'),
  ('220', 'washington_dc', 'Northern Virginia', 'VA'),
  ('221', 'washington_dc', 'Northern Virginia', 'VA'),
  ('222', 'washington_dc', 'Arlington', 'VA'),
  ('223', 'washington_dc', 'Alexandria', 'VA'),
  ('300', 'atlanta_ga', 'Atlanta', 'GA'),
  ('301', 'atlanta_ga', 'Atlanta', 'GA'),
  ('302', 'atlanta_ga', 'Atlanta', 'GA'),
  ('330', 'miami_fl', 'Miami', 'FL'),
  ('332', 'miami_fl', 'Miami', 'FL'),
  ('333', 'miami_fl', 'Fort Lauderdale', 'FL'),
  ('334', 'miami_fl', 'West Palm Beach', 'FL'),
  ('335', 'miami_fl', 'Tampa Bay', 'FL'),
  ('336', 'miami_fl', 'Tampa', 'FL'),
  ('337', 'miami_fl', 'St Petersburg', 'FL'),
  ('338', 'miami_fl', 'Lakeland', 'FL'),
  ('339', 'miami_fl', 'Fort Myers', 'FL'),
  ('440', 'cleveland_oh', 'Cleveland', 'OH'),
  ('442', 'cleveland_oh', 'Akron', 'OH'),
  ('443', 'cleveland_oh', 'Akron', 'OH'),
  ('444', 'cleveland_oh', 'Youngstown', 'OH'),
  ('445', 'cleveland_oh', 'Youngstown', 'OH'),
  ('446', 'cleveland_oh', 'Canton', 'OH'),
  ('447', 'cleveland_oh', 'Canton', 'OH'),
  ('448', 'cleveland_oh', 'North Central Ohio', 'OH'),
  ('449', 'cleveland_oh', 'Mansfield', 'OH'),
  ('600', 'chicago_il', 'North Chicagoland', 'IL'),
  ('601', 'chicago_il', 'West Chicagoland', 'IL'),
  ('602', 'chicago_il', 'Evanston', 'IL'),
  ('603', 'chicago_il', 'Oak Park', 'IL'),
  ('604', 'chicago_il', 'South Chicagoland', 'IL'),
  ('605', 'chicago_il', 'Naperville', 'IL'),
  ('607', 'chicago_il', 'Norridge', 'IL'),
  ('608', 'chicago_il', 'South Suburbs', 'IL'),
  ('750', 'dallas_tx', 'Dallas', 'TX'),
  ('751', 'dallas_tx', 'Dallas', 'TX'),
  ('753', 'dallas_tx', 'Dallas', 'TX'),
  ('754', 'dallas_tx', 'Dallas', 'TX'),
  ('760', 'dallas_tx', 'Fort Worth', 'TX'),
  ('761', 'dallas_tx', 'Fort Worth', 'TX'),
  ('762', 'dallas_tx', 'Denton', 'TX'),
  ('763', 'dallas_tx', 'Wichita Falls', 'TX'),
  ('764', 'dallas_tx', 'Stephenville', 'TX'),
  ('765', 'dallas_tx', 'Temple', 'TX'),
  ('766', 'dallas_tx', 'Waco Area', 'TX'),
  ('767', 'dallas_tx', 'Waco', 'TX'),
  ('768', 'dallas_tx', 'Brownwood', 'TX'),
  ('769', 'dallas_tx', 'San Angelo', 'TX'),
  ('772', 'houston_tx', 'Houston', 'TX'),
  ('773', 'houston_tx', 'North Houston', 'TX'),
  ('774', 'houston_tx', 'West Houston', 'TX'),
  ('775', 'houston_tx', 'Baytown', 'TX'),
  ('776', 'houston_tx', 'Beaumont', 'TX'),
  ('777', 'houston_tx', 'Beaumont', 'TX'),
  ('778', 'houston_tx', 'College Station', 'TX'),
  ('779', 'houston_tx', 'Victoria', 'TX'),
  ('800', 'denver_co', 'Aurora', 'CO'),
  ('801', 'denver_co', 'South Metro Denver', 'CO'),
  ('803', 'denver_co', 'Boulder', 'CO'),
  ('804', 'denver_co', 'Mountain Foothills', 'CO'),
  ('805', 'denver_co', 'Fort Collins', 'CO'),
  ('806', 'denver_co', 'Greeley', 'CO'),
  ('807', 'denver_co', 'Northeast Colorado', 'CO'),
  ('808', 'denver_co', 'Colorado Springs Region', 'CO'),
  ('809', 'denver_co', 'Colorado Springs', 'CO'),
  ('851', 'phoenix_az', 'Phoenix East Valley', 'AZ'),
  ('852', 'phoenix_az', 'Scottsdale and Mesa', 'AZ'),
  ('853', 'phoenix_az', 'Phoenix West Valley', 'AZ'),
  ('854', 'phoenix_az', 'Northeast Arizona', 'AZ'),
  ('855', 'phoenix_az', 'East Central Arizona', 'AZ'),
  ('856', 'phoenix_az', 'Southeast Arizona', 'AZ'),
  ('857', 'phoenix_az', 'Tucson', 'AZ'),
  ('858', 'phoenix_az', 'Tucson', 'AZ'),
  ('859', 'phoenix_az', 'Northeast Arizona', 'AZ'),
  ('901', 'los_angeles_ca', 'Los Angeles', 'CA'),
  ('902', 'los_angeles_ca', 'Los Angeles Westside', 'CA'),
  ('903', 'los_angeles_ca', 'Inglewood', 'CA'),
  ('904', 'los_angeles_ca', 'Santa Monica', 'CA'),
  ('905', 'los_angeles_ca', 'Torrance', 'CA'),
  ('906', 'los_angeles_ca', 'Whittier', 'CA'),
  ('907', 'los_angeles_ca', 'Long Beach Area', 'CA'),
  ('908', 'los_angeles_ca', 'Long Beach', 'CA'),
  ('909', 'los_angeles_ca', 'Inland Empire', 'CA'),
  ('910', 'los_angeles_ca', 'San Gabriel Valley', 'CA'),
  ('911', 'los_angeles_ca', 'Pasadena', 'CA'),
  ('912', 'los_angeles_ca', 'Glendale', 'CA'),
  ('913', 'los_angeles_ca', 'San Fernando Valley', 'CA'),
  ('914', 'los_angeles_ca', 'Van Nuys', 'CA'),
  ('915', 'los_angeles_ca', 'Burbank', 'CA'),
  ('916', 'los_angeles_ca', 'North Hollywood', 'CA'),
  ('917', 'los_angeles_ca', 'Pomona Valley', 'CA'),
  ('918', 'los_angeles_ca', 'Alhambra', 'CA'),
  ('919', 'san_francisco_ca', 'South Bay Fringe', 'CA'),
  ('920', 'san_francisco_ca', 'North San Diego County', 'CA'),
  ('921', 'san_francisco_ca', 'San Diego', 'CA'),
  ('922', 'los_angeles_ca', 'Palm Springs', 'CA'),
  ('923', 'los_angeles_ca', 'San Bernardino', 'CA'),
  ('924', 'los_angeles_ca', 'San Bernardino', 'CA'),
  ('925', 'los_angeles_ca', 'Riverside', 'CA'),
  ('926', 'los_angeles_ca', 'Orange County', 'CA'),
  ('927', 'los_angeles_ca', 'Santa Ana', 'CA'),
  ('928', 'los_angeles_ca', 'Anaheim', 'CA'),
  ('930', 'los_angeles_ca', 'Ventura County', 'CA'),
  ('931', 'los_angeles_ca', 'Santa Barbara', 'CA'),
  ('932', 'los_angeles_ca', 'Central Valley South', 'CA'),
  ('933', 'los_angeles_ca', 'Bakersfield', 'CA'),
  ('934', 'los_angeles_ca', 'Central Coast', 'CA'),
  ('935', 'los_angeles_ca', 'Antelope Valley', 'CA'),
  ('936', 'san_francisco_ca', 'Fresno Region', 'CA'),
  ('937', 'san_francisco_ca', 'Fresno', 'CA'),
  ('938', 'san_francisco_ca', 'Fresno', 'CA'),
  ('939', 'san_francisco_ca', 'Monterey Bay', 'CA'),
  ('940', 'san_francisco_ca', 'San Mateo County', 'CA'),
  ('942', 'san_francisco_ca', 'Sacramento', 'CA'),
  ('943', 'san_francisco_ca', 'Palo Alto', 'CA'),
  ('944', 'san_francisco_ca', 'San Mateo', 'CA'),
  ('945', 'san_francisco_ca', 'East Bay', 'CA'),
  ('946', 'san_francisco_ca', 'Oakland', 'CA'),
  ('947', 'san_francisco_ca', 'Berkeley', 'CA'),
  ('948', 'san_francisco_ca', 'Richmond', 'CA'),
  ('949', 'san_francisco_ca', 'Marin County', 'CA'),
  ('950', 'san_francisco_ca', 'South Bay', 'CA'),
  ('951', 'san_francisco_ca', 'San Jose', 'CA'),
  ('952', 'san_francisco_ca', 'Stockton', 'CA'),
  ('953', 'san_francisco_ca', 'Modesto', 'CA'),
  ('954', 'san_francisco_ca', 'North Bay', 'CA'),
  ('955', 'san_francisco_ca', 'North Coast', 'CA'),
  ('956', 'san_francisco_ca', 'Sacramento Region', 'CA'),
  ('957', 'san_francisco_ca', 'Sacramento Region', 'CA'),
  ('958', 'san_francisco_ca', 'Sacramento', 'CA'),
  ('959', 'san_francisco_ca', 'North Sacramento Valley', 'CA'),
  ('960', 'san_francisco_ca', 'Redding', 'CA'),
  ('961', 'san_francisco_ca', 'Sierra Nevada', 'CA'),
  ('970', 'seattle_wa', 'Portland Metro', 'OR'),
  ('971', 'seattle_wa', 'Portland Metro', 'OR'),
  ('972', 'seattle_wa', 'Portland', 'OR'),
  ('973', 'seattle_wa', 'Salem', 'OR'),
  ('974', 'seattle_wa', 'Eugene', 'OR'),
  ('975', 'seattle_wa', 'Medford', 'OR'),
  ('976', 'seattle_wa', 'Klamath Falls', 'OR'),
  ('977', 'seattle_wa', 'Bend', 'OR'),
  ('978', 'seattle_wa', 'Eastern Oregon', 'OR'),
  ('979', 'seattle_wa', 'Eastern Oregon', 'OR'),
  ('980', 'seattle_wa', 'Eastside Seattle', 'WA'),
  ('982', 'seattle_wa', 'Everett', 'WA'),
  ('983', 'seattle_wa', 'Tacoma Region', 'WA'),
  ('984', 'seattle_wa', 'Tacoma', 'WA'),
  ('985', 'seattle_wa', 'Olympia', 'WA'),
  ('986', 'seattle_wa', 'Vancouver WA', 'WA'),
  ('987', 'seattle_wa', 'Southeast Washington', 'WA'),
  ('988', 'seattle_wa', 'Central Washington', 'WA'),
  ('989', 'seattle_wa', 'Yakima', 'WA'),
  ('990', 'seattle_wa', 'Spokane Region', 'WA'),
  ('991', 'seattle_wa', 'Northeast Washington', 'WA'),
  ('992', 'seattle_wa', 'Spokane', 'WA'),
  ('993', 'seattle_wa', 'Tri-Cities', 'WA'),
  ('994', 'seattle_wa', 'Southeast Washington', 'WA')
on conflict (zip_prefix) do update set
  market_code = excluded.market_code,
  city = excluded.city,
  state_code = excluded.state_code;